'use client'

import { IdeaObject } from "@/types/niche"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { 
  Sparkles, 
  TrendingUp, 
  Smartphone, 
  Layout, 
  Copy, 
  Check, 
  CalendarDays,
  Share2,
  X,
  Zap,
  Lightbulb,
  FileText,
  Download,
  ExternalLink,
  MessageSquare,
  ChevronLeft,
  Wand2,
  Loader2,
  History
} from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"
import { Teleprompter } from "@/components/dashboard/Teleprompter"
import { cn } from "@/lib/utils"
import { shareIdeaAction } from "@/app/actions/ideas"
import { remixScriptAction } from "@/app/actions/remix"

interface StrategicBriefModalProps {
  idea: IdeaObject
  ideaId?: string
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  onSchedule: () => void
}

export function StrategicBriefModal({ 
  idea, 
  ideaId,
  isOpen, 
  onOpenChange,
  onSchedule
}: StrategicBriefModalProps) {
  const [isPrompterOpen, setIsPrompterOpen] = useState(false)
  const [isSharing, setIsSharing] = useState(false)
  const [remixInstruction, setRemixInstruction] = useState('')
  const [isRemixing, setIsRemixing] = useState(false)
  const [currentIdea, setCurrentIdea] = useState<IdeaObject>(idea)

  const copyToClipboard = (text: string, msg = "Copied to clipboard!") => {
    navigator.clipboard.writeText(text)
    toast.success(msg)
  }

  const exportAsMarkdown = () => {
    const content = `# ${currentIdea.title}\n\n## Hook\n${currentIdea.hook}\n\n## Strategy\n${currentIdea.description}\n\n## Script\n${currentIdea.scriptDraft || 'No script drafted.'}\n\n---\nGenerated by RepsBrief Studio`
    const blob = new Blob([content], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${currentIdea.title.toLowerCase().replace(/\s+/g, '-')}.md`
    a.click()
    URL.revokeObjectURL(url)
    toast.success("Markdown brief downloaded!")
  }

  const copyForNotion = () => {
    const content = `# ${currentIdea.title}\n\n**Hook:** ${currentIdea.hook}\n\n**Strategy:**\n${currentIdea.description}\n\n**Script:**\n${currentIdea.scriptDraft || 'N/A'}`
    copyToClipboard(content, "Formatted for Notion!")
  }

  const handleSaveStrategy = async () => {
    setIsSharing(true)
    const tid = toast.loading("Generating public link...")
    try {
      const res = await shareIdeaAction(currentIdea, currentIdea.niche || 'fitness')
      if (res.success && res.shareId) {
        const url = `${window.location.origin}/share/${res.shareId}`
        navigator.clipboard.writeText(url)
        toast.success("Strategy saved & Link copied!", { id: tid })
      } else {
        toast.error("Failed to save strategy", { id: tid })
      }
    } catch (err) {
      toast.error("Error sharing strategy", { id: tid })
    } finally {
      setIsSharing(false)
    }
  }

  const handleRemix = async () => {
    if (!remixInstruction) return
    setIsRemixing(true)
    const tid = toast.loading("AI is remixing your strategy...")
    try {
      const res = await remixScriptAction(currentIdea, remixInstruction)
      if (res.success && res.data) {
        setCurrentIdea({
          ...currentIdea,
          hook: res.data.newHook,
          scriptDraft: res.data.newScript,
          whyItWorks: res.data.explanation
        })
        setRemixInstruction('')
        toast.success("Remix complete!", { id: tid })
      } else {
        toast.error(res.error || "Failed to remix", { id: tid })
      }
    } catch (err) {
      toast.error("Error connecting to AI", { id: tid })
    } finally {
      setIsRemixing(false)
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-[100vw] w-screen h-[100vh] m-0 p-0 bg-[#050505] border-none text-slate-50 shadow-none flex flex-col rounded-none overflow-hidden selection:bg-blue-500/30">
        
        <DialogHeader className="sr-only">
          <DialogTitle>{currentIdea.title}</DialogTitle>
          <DialogDescription>Full Screen Strategic Studio for {currentIdea.title}.</DialogDescription>
        </DialogHeader>

        {/* Global Decor */}
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-blue-600/[0.03] rounded-full blur-[160px] pointer-events-none" />
        
        {/* Main Studio Header */}
        <div className="h-20 border-b border-white/5 flex items-center justify-between px-8 bg-black/40 backdrop-blur-xl relative z-[100]">
          <div className="flex items-center gap-6 text-left">
            <Button 
              variant="ghost" 
              onClick={() => onOpenChange(false)}
              className="h-10 pl-2 pr-4 rounded-full bg-white/5 border border-white/10 text-slate-400 hover:text-white transition-all gap-2"
            >
              <ChevronLeft className="w-4 h-4" />
              <span className="text-[10px] font-black uppercase tracking-widest">Dashboard</span>
            </Button>
            <div className="h-6 w-px bg-white/10" />
            <div className="flex items-center gap-3 text-left">
              <Badge variant="outline" className="bg-blue-500/10 text-blue-400 border-blue-500/20 px-3 py-0.5 rounded-full text-[9px] font-black tracking-[0.2em] uppercase">
                {currentIdea.format} STUDIO
              </Badge>
              <h2 className="text-lg font-bold text-white tracking-tight truncate max-w-md">
                {currentIdea.title}
              </h2>
            </div>
          </div>

          <div className="flex items-center gap-4 text-left">
             <div className="hidden md:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-emerald-500/5 border border-emerald-500/10">
                <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-[9px] font-black text-emerald-500 uppercase tracking-widest">Strategic Sync Active</span>
             </div>
             <button 
              onClick={() => onOpenChange(false)}
              className="w-10 h-10 rounded-full flex items-center justify-center bg-white/5 hover:bg-rose-500/20 hover:text-rose-400 text-slate-500 transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Area: Two-Column Layout */}
        <div className="flex-1 flex overflow-hidden relative z-10">
          
          {/* Left Column: Strategic Content (Scrollable) */}
          <div className="flex-1 overflow-y-auto custom-scrollbar p-12 lg:p-20 space-y-20 pb-40 text-left">
            
            {/* The Hook Section */}
            <section className="max-w-4xl mx-auto space-y-8 text-left">
              <div className="flex items-center gap-3 px-1">
                <div className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em]">Phase 01: Attention Architecture</span>
              </div>
              <div className="relative group text-left">
                <div className="absolute -inset-1 bg-gradient-to-r from-blue-600/10 to-emerald-600/10 rounded-[3rem] blur-2xl opacity-0 group-hover:opacity-100 transition duration-1000" />
                <div className="relative p-12 md:p-16 rounded-[3rem] bg-white/[0.02] border border-white/5 text-left overflow-hidden">
                  <div className="absolute top-0 right-0 p-8 opacity-[0.02] pointer-events-none">
                    <TrendingUp className="w-40 h-40" />
                  </div>
                  <h3 className="text-[10px] font-black text-blue-400 uppercase tracking-widest mb-6">The Viral Hook</h3>
                  <p className="text-3xl md:text-4xl italic text-white leading-tight font-light selection:bg-blue-500/50">
                    &ldquo;{currentIdea.hook}&rdquo;
                  </p>
                  <div className="mt-10 flex items-center gap-4">
                    <Button 
                      variant="ghost" 
                      className="h-10 px-5 rounded-full bg-white/5 border border-white/10 text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-white gap-2"
                      onClick={() => copyToClipboard(currentIdea.hook)}
                    >
                      <Copy className="w-3.5 h-3.5" />
                      Copy Hook
                    </Button>
                  </div>
                </div>
              </div>
            </section>

            {/* Strategy & Script Grid */}
            <section className="max-w-4xl mx-auto space-y-12 text-left">
               <div className="flex items-center gap-3 px-1">
                <div className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.3em]">Phase 02: Execution Logic</span>
              </div>
              
              <div className="space-y-6 text-left">
                <div className="flex items-center justify-between">
                   <h4 className="text-xs font-black text-white uppercase tracking-widest">Full Production Script</h4>
                   {(currentIdea.scriptDraft || currentIdea.description) && (
                     <Button 
                        onClick={() => setIsPrompterOpen(true)}
                        className="h-9 px-5 rounded-full bg-purple-600 hover:bg-purple-500 text-white font-black text-[10px] uppercase tracking-widest gap-2 shadow-lg shadow-purple-500/20 transition-all"
                      >
                        <Smartphone className="w-3.5 h-3.5" />
                        Live Recording Mode
                      </Button>
                   )}
                </div>
                
                <div className="relative p-10 rounded-[2.5rem] bg-black border border-white/5 group text-left shadow-2xl">
                  <div className="absolute top-6 right-6">
                     <Button 
                       variant="ghost" 
                       size="icon" 
                       className="h-10 w-10 text-slate-600 hover:text-white bg-white/5 rounded-full"
                       onClick={() => copyToClipboard(currentIdea.scriptDraft || currentIdea.description)}
                     >
                       <Copy className="w-4 h-4" />
                     </Button>
                  </div>
                  <div className="prose prose-invert max-w-none text-left">
                    <p className="text-base md:text-lg text-slate-300 leading-relaxed font-mono whitespace-pre-wrap selection:bg-purple-500/30 text-left">
                      {currentIdea.scriptDraft || currentIdea.description}
                    </p>
                  </div>
                </div>
              </div>
            </section>

          </div>

          {/* Right Column: FIXED Sidebar (Remix & Meta) */}
          <div className="w-[400px] border-l border-white/5 bg-white/[0.01] backdrop-blur-md flex flex-col relative z-20 text-left">
            <div className="flex-1 overflow-y-auto p-8 space-y-10 custom-scrollbar text-left">
              
              {/* Remix Tool Section */}
              <section className="space-y-6 text-left">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-blue-600/20 border border-blue-500/30 text-blue-400">
                    <Sparkles className="w-4 h-4" />
                  </div>
                  <h4 className="text-xs font-black text-white uppercase tracking-widest">AI Strategy Remix</h4>
                </div>
                
                <div className="space-y-4 text-left">
                  <p className="text-[11px] text-slate-500 leading-relaxed text-left">
                    Adjust the tone, lengthen the hook, or adapt this strategy for a specific trend.
                  </p>
                  <div className="relative group text-left">
                    <Textarea 
                      placeholder="e.g. 'Make it more aggressive', 'Translate to Italian', 'Add a call to action at the end'..."
                      value={remixInstruction}
                      onChange={(e) => setRemixInstruction(e.target.value)}
                      className="min-h-[120px] bg-black border-white/10 rounded-2xl p-4 text-sm text-slate-300 focus:border-blue-500/50 transition-all resize-none text-left"
                    />
                    <div className="absolute bottom-3 right-3 text-left">
                       <Button 
                        size="sm"
                        disabled={!remixInstruction || isRemixing}
                        onClick={handleRemix}
                        className="h-8 rounded-lg bg-blue-600 hover:bg-blue-500 text-white font-black text-[9px] uppercase tracking-widest gap-2 px-3 transition-all active:scale-95 text-left"
                       >
                         {isRemixing ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand2 className="w-3 h-3" />}
                         Apply Remix
                       </Button>
                    </div>
                  </div>
                </div>
              </section>

              {/* Why it Works Section */}
              <section className="p-6 rounded-[2rem] bg-emerald-500/[0.03] border border-emerald-500/10 space-y-4 text-left relative overflow-hidden">
                <div className="absolute top-0 right-0 p-4 opacity-[0.05]">
                  <Lightbulb className="w-20 h-20 text-emerald-500" />
                </div>
                <div className="flex items-center gap-2">
                  <Sparkles className="w-3.5 h-3.5 text-emerald-400" />
                  <span className="text-[9px] font-black text-emerald-500/70 uppercase tracking-widest">Growth Logic</span>
                </div>
                <p className="text-xs text-emerald-100/80 leading-relaxed font-medium italic relative z-10 text-left">
                  {currentIdea.whyItWorks}
                </p>
              </section>

              {/* Smart Metadata */}
              <section className="space-y-6 text-left">
                 <div className="flex items-center gap-3">
                  <div className="p-2 rounded-xl bg-white/5 border border-white/10 text-slate-400">
                    <History className="w-4 h-4" />
                  </div>
                  <h4 className="text-xs font-black text-white uppercase tracking-widest">Production Data</h4>
                </div>
                
                <div className="grid grid-cols-1 gap-3">
                   <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center justify-between">
                      <span className="text-[10px] font-bold text-slate-500 uppercase">Target Niche</span>
                      <span className="text-[10px] font-black text-white uppercase tracking-widest">{currentIdea.niche || 'General'}</span>
                   </div>
                   <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 flex items-center justify-between">
                      <span className="text-[10px] font-bold text-slate-500 uppercase">Platform Opt.</span>
                      <span className="text-[10px] font-black text-blue-400 uppercase tracking-widest">{currentIdea.format}</span>
                   </div>
                </div>

                <Button 
                  onClick={onSchedule}
                  className="w-full h-12 rounded-2xl bg-white/5 border border-white/10 text-white hover:bg-white/10 font-bold gap-3 justify-center text-left"
                >
                  <CalendarDays className="w-4 h-4 text-blue-400" />
                  Schedule Production
                </Button>
              </section>

            </div>
          </div>
        </div>

        {/* Studio Distribution Footer (26px height, centered) */}
        <div className="absolute bottom-8 left-1/2 -translate-x-1/2 z-[200] flex items-center gap-2 p-1.5 rounded-full bg-black/80 border border-white/10 backdrop-blur-3xl shadow-[0_20px_50px_rgba(0,0,0,0.5)] ring-1 ring-white/5">
           <Button 
             variant="ghost" 
             className="h-[26px] px-4 rounded-full text-[9px] font-black uppercase tracking-[0.15em] text-slate-400 hover:text-white hover:bg-white/10 gap-2 transition-all group"
             onClick={copyForNotion}
           >
             <div className="w-1 h-1 rounded-full bg-slate-600 group-hover:bg-blue-400 transition-colors" />
             NOTION
           </Button>
           <div className="w-px h-3 bg-white/10" />
           <Button 
             variant="ghost" 
             className="h-[26px] px-4 rounded-full text-[9px] font-black uppercase tracking-[0.15em] text-slate-400 hover:text-white hover:bg-white/10 gap-2 transition-all group"
             onClick={exportAsMarkdown}
           >
             <div className="w-1 h-1 rounded-full bg-slate-600 group-hover:bg-blue-400 transition-colors" />
             BRIEF.MD
           </Button>
           <div className="w-px h-3 bg-white/10" />
           <Button 
             variant="ghost" 
             className="h-[26px] px-4 rounded-full text-[9px] font-black uppercase tracking-[0.15em] text-slate-400 hover:text-white hover:bg-white/10 gap-2 transition-all group"
             onClick={handleSaveStrategy}
             disabled={isSharing}
           >
             <div className="w-1.5 h-1.5 rounded-full bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.8)]" />
             SAVE STRATEGY
           </Button>
        </div>

        {/* Global Floating Teleprompter */}
        {isPrompterOpen && (
          <Teleprompter 
            title={currentIdea.title} 
            script={currentIdea.scriptDraft || currentIdea.description} 
            onClose={() => setIsPrompterOpen(false)} 
          />
        )}
      </DialogContent>
    </Dialog>
  )
}
