import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import { PublicStudioShell, publicStudioClasses } from '@/components/layout/PublicStudioShell'

export const metadata = {
  title: 'Terms of Service — RepsBrief',
  description: 'Terms governing your use of the RepsBrief platform.',
}

export default function TermsPage() {
  const lastUpdated = 'April 3, 2026'

  return (
    <PublicStudioShell contentClassName="max-w-4xl">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-slate-500 hover:text-white text-sm font-medium transition-colors mb-12"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to RepsBrief
        </Link>

        <p className={`${publicStudioClasses.metadata} mb-2`}>Legal</p>
        <h1 className="text-4xl font-semibold text-white tracking-tight mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: {lastUpdated}</p>

        <div className="space-y-10 text-sm leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">1. Acceptance</h2>
            <p className="text-slate-400">
              By creating an account or using RepsBrief (&ldquo;Service&rdquo;), you agree to these Terms of
              Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">2. Description of service</h2>
            <p className="text-slate-400">
              RepsBrief is a SaaS platform that generates AI-powered content briefs from real-time trend data.
              It is available on a free Starter plan and paid Pro/Team plans.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">3. Accounts</h2>
            <p className="text-slate-400">
              You are responsible for maintaining the confidentiality of your account credentials. You must
              provide accurate information at signup. We reserve the right to suspend accounts that violate
              these Terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">4. Subscriptions and billing</h2>
            <ul className="list-disc list-inside space-y-2 text-slate-400">
              <li>Paid plans are billed monthly via Stripe. Prices are shown at checkout.</li>
              <li>Pro plans include a 7-day free trial. No charge is made until the trial ends.</li>
              <li>You may cancel at any time through your billing portal. Access continues until the end of the current billing period.</li>
              <li>We reserve the right to change pricing with 30 days&rsquo; notice.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">5. Acceptable use</h2>
            <p className="text-slate-400">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 text-slate-400">
              <li>Use the Service to generate spam, misleading content, or content that violates applicable law.</li>
              <li>Reverse-engineer, copy, or redistribute the platform or its AI outputs for competitive purposes.</li>
              <li>Attempt to circumvent plan limits or access controls.</li>
              <li>Use the Service in any way that overloads or disrupts our infrastructure.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">6. Intellectual property</h2>
            <p className="text-slate-400">
              Content briefs and ideas generated by RepsBrief using your inputs are owned by you. The platform,
              its design, algorithms and underlying code remain the property of RepsBrief.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">7. Disclaimer of warranties</h2>
            <p className="text-slate-400">
              The Service is provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee
              that AI-generated content is accurate, complete or suitable for any particular purpose. You use
              AI outputs at your own discretion.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">8. Limitation of liability</h2>
            <p className="text-slate-400">
              To the maximum extent permitted by law, RepsBrief shall not be liable for any indirect, incidental,
              or consequential damages arising from your use of the Service. Our total liability shall not exceed
              the amount you paid in the 3 months prior to the claim.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">9. Termination</h2>
            <p className="text-slate-400">
              We may suspend or terminate your account for violation of these Terms. You may delete your account
              at any time from Settings. Upon termination, your data will be deleted within 30 days.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">10. Governing law</h2>
            <p className="text-slate-400">
              These Terms are governed by Italian law. Any disputes shall be resolved in the courts of Milan, Italy.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-white">11. Contact</h2>
            <p className="text-slate-400">
              Questions? Email <a href="mailto:legal@repsbrief.com" className="text-blue-400 hover:text-blue-300">legal@repsbrief.com</a>.
            </p>
          </section>
        </div>
      </div>
    </PublicStudioShell>
  )
}
