"use server"

import { createCalendarEvent } from "@/lib/integrations/google"
import { createClient } from "@/lib/supabase/server"

export async function syncToGoogleCalendarAction(teamId: string, ideaId: string, scheduledDate?: string) {
  try {
    const supabase = await createClient()
    console.log(`[CalendarSync] Syncing idea ${ideaId} for team ${teamId}`)

    // 1. Recupero i dettagli dell'idea senza join restrittive
    const { data: idea, error: ideaError } = await supabase
      .from('idea_history')
      .select('*')
      .eq('id', ideaId)
      .maybeSingle()

    if (ideaError || !idea) {
      console.error(`[CalendarSync] Idea ${ideaId} not found or error:`, ideaError)
      throw new Error('Idea non trovata nel database')
    }

    // 2. Prepariamo i contenuti per l'evento
    const title = idea.idea_title || "New Content Idea"
    const ideaData = idea.idea_data || {}
    
    const description = `
🎬 RepsBrief Strategy
---
💡 Hook: ${ideaData.hook || 'N/A'}
📐 Angle: ${ideaData.angle || 'N/A'}
✅ Why it works: ${ideaData.why_it_works || ideaData.whyItWorks || 'N/A'}
---
Generated by RepsBrief
    `.trim()

    // LOGICA DATA INTELLIGENTE
    let date = scheduledDate ? new Date(scheduledDate) : new Date()
    
    if (!scheduledDate) {
      // Se non c'è una data, proviamo a metterlo domani alle 10:00
      date.setDate(date.getDate() + 1)
      date.setHours(10, 0, 0, 0)
    }

    const startDateTime = date.toISOString()
    const endDateTime = new Date(date.getTime() + 60 * 60 * 1000).toISOString() // 1 ora di durata

    // 3. Creazione evento
    const result = await createCalendarEvent(teamId, {
      summary: title,
      description,
      startDateTime,
      endDateTime
    })

    // 4. Logghiamo l'esportazione (opzionale)
    await supabase.from('team_integration_logs').insert({
      team_id: teamId,
      provider: 'google_calendar',
      action: 'sync_event',
      status: 'success',
      details: { event_id: result.id, idea_id: ideaId }
    })

    return { success: true, eventUrl: result.htmlLink }

  } catch (error: any) {
    console.error("Sync to Google Calendar failed:", error)
    return { success: false, error: error.message || "Errore durante la sincronizzazione" }
  }
}
