"use server"

import { createCalendarEvent } from "@/lib/integrations/google"
import { createClient } from "@/lib/supabase/server"

/**
 * Sincronizza un singolo evento (Idea o Manuale) con Google Calendar
 */
export async function syncToGoogleCalendarAction(teamId: string, ref: { ideaId?: string, calendarId?: string }, scheduledDate?: string) {
  try {
    const supabase = await createClient()
    let title = ""
    let description = ""
    let targetDate = scheduledDate

    // 1. Recupero i dati (da idea_history o da content_calendar)
    if (ref.calendarId) {
      const { data: entry } = await supabase
        .from('content_calendar')
        .select('*')
        .eq('id', ref.calendarId)
        .single()
      
      if (!entry) throw new Error('Evento non trovato')
      title = entry.title
      description = `
📱 Platform: ${entry.platform.toUpperCase()}
📝 Notes: ${entry.notes || 'N/A'}
---
Managed via RepsBrief Editorial Calendar
      `.trim()
      if (!targetDate) targetDate = entry.scheduled_date
    } else if (ref.ideaId) {
      const { data: idea } = await supabase
        .from('idea_history')
        .select('*')
        .eq('id', ref.ideaId)
        .single()
      
      if (!idea) throw new Error('Idea non trovata')
      title = idea.idea_title || "New Content Idea"
      const ideaData = idea.idea_data || {}
      description = `
🎬 RepsBrief Strategy
---
💡 Hook: ${ideaData.hook || 'N/A'}
📐 Angle: ${ideaData.angle || 'N/A'}
✅ Why it works: ${ideaData.why_it_works || ideaData.whyItWorks || 'N/A'}
---
Generated by RepsBrief
      `.trim()
    }

    if (!targetDate) targetDate = new Date().toISOString()
    const date = new Date(targetDate)
    const startDateTime = date.toISOString()
    const endDateTime = new Date(date.getTime() + 60 * 60 * 1000).toISOString()

    // 2. Creazione evento su Google
    const result = await createCalendarEvent(teamId, {
      summary: title,
      description,
      startDateTime,
      endDateTime
    })

    // 3. Salviamo il riferimento dell'evento Google nel nostro DB per evitare duplicati futuri
    if (ref.calendarId) {
      await supabase
        .from('content_calendar')
        .update({ 
          metadata: { google_event_id: result.id, google_link: result.htmlLink } 
        })
        .eq('id', ref.calendarId)
    }

    return { success: true, eventUrl: result.htmlLink }

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Errore durante la sincronizzazione"
    console.error("Sync to Google Calendar failed:", error)
    return { success: false, error: message }
  }
}

/**
 * Sincronizza TUTTI gli eventi futuri non ancora sincronizzati
 */
export async function bulkSyncFutureEventsAction(teamId: string) {
  try {
    const supabase = await createClient()

    // 1. Recupero eventi futuri che non hanno ancora un google_event_id
    const { data: entries, error } = await supabase
      .from('content_calendar')
      .select('*')
      .eq('team_id', teamId)
      .gte('scheduled_date', new Date().toISOString())
      .filter('metadata->google_event_id', 'is', null)

    if (error) throw error
    if (!entries || entries.length === 0) return { success: true, syncedCount: 0 }

    let syncedCount = 0
    for (const entry of entries) {
      const res = await syncToGoogleCalendarAction(teamId, { calendarId: entry.id }, entry.scheduled_date)
      if (res.success) syncedCount++
    }

    return { success: true, syncedCount }

  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Bulk sync failed"
    console.error("Bulk sync failed:", error)
    return { success: false, error: message }
  }
}
